description: "Animal Legs Eval"

prompts:
  - prompts.py:simple_prompt
  - prompts.py:better_prompt
  - prompts.py:chain_of_thought_prompt
  
providers:
  - anthropic:messages:claude-haiku-4-5-20251001
  - anthropic:messages:claude-sonnet-4-5-20250929

tests: animal_legs_tests.csv

defaultTest:
  options:
    transform: file://transform.py


